name: "Continuous Deployment"

on:
  push:
    branches:
      - master

jobs:
  deploy_to_heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_TOKEN}}
          heroku_app_name: aventus-devsecops-test
          heroku_email: 8antonm@gmail.com