name: "Continuous Deployment to Test"

on:
  push:
    branches:
      - master

jobs:
  code_security_test_DAST:
    name: DAST
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          target: https://devops-db-application.herokuapp.com